name: Monitor INAP cada 30 minutos

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  check-inap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Obtener run ID anterior
        id: previous
        run: echo "run_id=$(( ${{ github.run_id }} - 1 ))" >> $GITHUB_OUTPUT

      - name: Descargar estado previo
        uses: actions/download-artifact@v4
        with:
          name: inap-state
          path: ./artifact-state
          run-id: ${{ steps.previous.outputs.run_id }}
        continue-on-error: true

      - name: Mover state.json si existe
        run: |
          if [ -f "./artifact-state/state.json" ]; then
            mv ./artifact-state/state.json ./state.json
          else
            echo '{"hash": ""}' > state.json
          fi

      - name: Mostrar estado actual
        run: cat state.json

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Guardar nuevo estado
        uses: actions/upload-artifact@v4
        with:
          name: inap-state
          path: state.json
