name: Monitor INAP cada 30 minutos

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  check-inap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py

      - name: Commit del nuevo estado si ha cambiado
        run: |
          if git diff --quiet state.json; then
            echo "No hay cambios en state.json, no se hace commit."
          else
            echo "Hay cambios en state.json, haciendo commit..."
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git add state.json
            git commit -m "Actualizar estado INAP"
            git push
          fi
